### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by ppuskar** [tsavecodes/vue-shopify#1]
'npm run serve' results in below exception

` 10% building 1/1 modules 0 activeevents.js:167                              
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ppuskar/work/codebase/github/vue-shopify/public'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1251:11)
    at createFsWatchInstance (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:155:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/ppuskar/work/codebase/github/vue-shopify/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:155:5)
`

**Comment by ppuskar** [comment]
vue:3.0.3
OS: Fedora 29
